#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")
print(env['CXXFLAGS'])

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

env.Append(CXXFLAGS=['-stdlib=libc++', '-std=c++20']);
env.Append(LINKFLAGS=['-stdlib=libc++']);

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH="Pathfinding_Tilemap/")
src = Glob("Pathfinding_Tilemap/*.cpp")

if env['platform'] == 'macos':
	libpath = 'pathfinder{}{}'.format( env['suffix'], env['SHLIBSUFFIX'] );
	sharedlib = env.SharedLibrary(libpath, src);
	Default(sharedlib);
